apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-js
  labels:
    name: app-js
spec:
  selector:
    matchLabels:
      app: app-js
  template:
    metadata:
      labels:
        app: app-js
    spec:
      volumes:
      - name: cache-volume
        hostPath:
          path: /cache
          type: Directory
      containers:
        - name: app-js
          image: appjs
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          volumeMounts:
          - mountPath: /cache
            name: cache-volume
  replicas: 3